# Change these first
owner: LencoDigitexer # Your GitHub organization or username, where this repository lives
repo: flibustang_uptime # The name of this repository

sites:
  - name: flibustang.ru
    url: https://flibustang.ru
  - name: flibustang.online
    url: https://flibustang.online

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /flibustang_uptime
  logoUrl: https://raw.githubusercontent.com/LencoDigitexer/flibustang_uptime/master/assets/logo.png
  name: FlibustaNG
  theme: dark
  introTitle: "**FlibustaNG** - поиск и чтение книг."
  introMessage: Статистика доступности сервиса
  navbar:
    - title: flibustang.ru
      href: https://flibustang.ru
    - title: flibustang.online
      href: https://flibustang.online
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
